name: TopicTracker
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.2.1
  - IPython=7.19.0
  - tqdm=4.55.1
  - matplotlib
  - spacy=2.3.5
  - wordcloud
  - spacy-model-en_core_web_md=2.3.1=pyh9f0ad1d_0
  - bokeh=2.2.3
  - numpy
  - ipywidgets
  - nbserverproxy
  - voila
  - pip
  - pip:
    - jupyter-server-proxy
    - shutils==0.1.0